apiVersion: apps/v1
kind: Deployment
metadata:
  name: bamboo-chat
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bamboo-chat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: bamboo-chat
    spec:
      containers:
        - name: bamboo-chat
          image: mohsenrzva/bamboo-chat:stable
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.5"
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: chat
              containerPort: 4005
          env:
            - name: ENABLE_APM
              value: "1"
            - name: NODE_ENV
              value: "production"
            - name: GATEWAY_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: gateway-jwt-token
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: jwt-token
            - name: RABBITMQ_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: bamboo-rabbitmq-endpoint
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: mongo-database-url
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: cloud-name
            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: cloud-api-key
            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: cloud-api-secret
            - name: API_GATEWAY_URL
              value: "http://bamboo-gateway.production.svc.cluster.local:4000"
            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: bamboo-elasticsearch-url
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: bamboo-elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: bamboo-elastic-apm-secret-token
