apiVersion: apps/v1
kind: Deployment
metadata:
  name: bamboo-gateway
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bamboo-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: bamboo-gateway
    spec:
      containers:
        - name: bamboo-gateway
          image: mohsenrzva/bamboo-gateway:stable
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: gateway
              containerPort: 4000
          env:
            - name: ENABLE_APM
              value: "1"
            - name: NODE_ENV
              value: "production"
            - name: SECRET_KEY_ONE
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: secret-key-one
            - name: SECRET_KEY_TWO
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: secret-key-two
            - name: GATEWAY_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: gateway-jwt-token
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: jwt-token
            - name: CLIENT_URL
              value: "https://bambooapp.info"
            - name: AUTH_BASE_URL
              value: "http://bamboo-auth.production.svc.cluster.local:4002"
            - name: USERS_BASE_URL
              value: "http://bamboo-users.production.svc.cluster.local:4003"
            - name: MESSAGE_BASE_URL
              value: "http://bamboo-chat.production.svc.cluster.local:4005"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: bamboo-redis-host
            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: bamboo-elasticsearch-url
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: bamboo-elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: bamboo-elastic-apm-secret-token
