apiVersion: apps/v1
kind: Deployment
metadata:
  name: bamboo-users
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bamboo-users
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: bamboo-users
    spec:
      containers:
        - name: bamboo-users
          image: mohsenrzva/bamboo-users:stable
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: users
              containerPort: 4003
          env:
            - name: ENABLE_APM
              value: "1"
            - name: NODE_ENV
              value: "production"
            - name: GATEWAY_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: gateway-jwt-token
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: jwt-token
            - name: RABBITMQ_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: bamboo-rabbitmq-endpoint
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: mongo-database-url
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: cloud-name
            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: cloud-api-key
            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: cloud-api-secret
            - name: API_GATEWAY_URL
              value: "http://bamboo-gateway.production.svc.cluster.local:4000"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: bamboo-redis-host
            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: bamboo-elasticsearch-url
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: bamboo-elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bamboo-backend-secret
                  key: bamboo-elastic-apm-secret-token
