apiVersion: v1
kind: Service
metadata:
  name: bamboo-redis
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: bamboo-redis
  ports:
    - name: bamboo-redis
      port: 6379
      targetPort: 6379
