apiVersion: v1
kind: Service
metadata:
  name: bamboo-mysql
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: bamboo-mysql
  ports:
    - name: bamboo-mysql
      port: 3306
      targetPort: 3306
